language: python
python:
  - 3.7
  - 3.6
  - 3.5
sudo: false
dist: xenial
cache:
  pip: true
before_install:
  - pip install -U pip setuptools
  - pip install codecov
install:
  - pip install --upgrade -e ".[test]"
script:
  - py.test -l --cov-report xml:$TRAVIS_BUILD_DIR/coverage.xml --cov=globmatch
after_success:
  - codecov
